name: webcoos_shoreline_detection
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python>=3.11,<3.12
  # API-related
  - fastapi<0.116.0
  - gunicorn
  - python-multipart
  - uvicorn
  - filetype
  - prometheus_client
  # Computation/method-related
  - matplotlib
  - numpy<2
  - pillow
  - scipy
  - scikit-image
  - statsmodels
  - pip
  # Testing related
  - flake8>=3.7.9
  - pytest
  - pytest-env
  - httpx
  - pip:
    - imagecodecs>=2024.6.1,<2024.7
    - opencv-python-headless>=4.9.0.80,<4.10
